### ISSUE TITLE
Temporary Lossless Governance contract

### ISSUE THREAD

**Issue by agiledev624** [Lossless-Cash/lossless-v3#100] opened 2022-03-21 23:01 UTC
Lossless Governance contract supports the functionality for wrongly reported smart contract to claim compensation.
If it was resolved negatively.
```
function _compensateAddresses(address[] memory _addresses) private {
        uint256 reportingAmount = losslessReporting.reportingAmount();
        uint256 compensationAmount = (reportingAmount * compensationPercentage) / HUNDRED;

        
        for(uint256 i = 0; i < _addresses.length;) {
            address singleAddress = _addresses[i];
            Compensation storage addressCompensation = compensation[singleAddress]; 

            // This line will perform the staking token transfer to the contract, I think?
            losslessController.resolvedNegatively(singleAddress);      

            addressCompensation.amount += compensationAmount;
            addressCompensation.payed = false;
            unchecked{i++;}
        }
    }
```
Please let me know if I misunderstand something. Thanks

**Comment by DomantasP** [comment] 2022-03-29 06:29
The problem is that in order to get the compensation reported address has to call `retrieveCompensation`. If reported address is some random smart contract that knows nothing about the lossless protocol it could not have the feature to call this function. If it's not upgradable there's no way for that reported smart contract to get the compensation.

I'm closing this issue as this will be addressed in the next version of the protocol.

**Closed by DomantasP** 2022-03-29 06:29 UTC

**Comment by agiledev624** [comment] 2022-03-29 06:35
I see. Because I had some code challenges for such stuff. And I thought the condition was the contract already knows the workflow.
So we need some steps like to make the contract get compensation passively?
